### ISSUE TITLE
Необходимо сохранять ссылки на соцсети

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos.io#101]
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/227060ad-3be8-47ff-a5f9-7bbfbccfb7e5)

**Comment by AlexandrDedckov** [comment]
Данные ссылки пробрасываются в EE. В БЧ мы их не храним. Ссылки на вк, фб и инсту уже есть

**Comment by daryasattarova** [comment]
![image](https://user-images.githubusercontent.com/42342756/60660644-d8089180-9e60-11e9-9b28-95afe21c3d6d.png)
нужно отображать ссылки иконками в краткой информации. при клике на иконку редиректить на соцсеть в новой вкладке
