### ISSUE TITLE
некорректно работает фильтр по тегам

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos.io#115]
(внутри поста тегов больше нет)
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/1d3e62fb-a445-4569-8025-9defd410763d)

**Comment by beautyfree** [comment]
Issue moved to [GolosChain/prism-service #373](https://github.com/GolosChain/prism-service/issues/373) via [**ZenHub**](https://www.zenhub.com/)
