### ISSUE TITLE
исправить текстовку, появляющуюся при попытке создать пост раньше чем через 5 минут с последнего постинга

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos.io#117]
сейчас она такая. заменить на "говорящую"
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/d89ea038-26cb-4792-bc91-d441e0473f42)

**Comment by beautyfree** [comment]
@daryasattarova нужно выяснить какая говорящая

**Comment by daryasattarova** [comment]
это не ко мне вопрос наверное. либо можно оставить, но прикрутить локализацию

**Comment by b1acksun** [comment]
https://github.com/GolosChain/golos.io/issues/529
