### ISSUE TITLE
при создании поста появляется ошибка "Post submitting failed"

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos.io#128]
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/aadd46bf-7ec4-4002-821b-7083cccf94a3)

**Comment by daryasattarova** [comment]
![image](https://user-images.githubusercontent.com/42342756/62621829-910d3080-b925-11e9-855d-7529f80812aa.png)
только что воспроизвелась в тестах

**Comment by b1acksun** [comment]
![image](https://user-images.githubusercontent.com/3322340/64153900-7781da80-ce38-11e9-8c3f-c0ac32584f4f.png)
