### ISSUE TITLE
ошибка при делегировании

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos.io#142]
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/b2cd454c-e22f-4520-a965-01c0deb5dab3)

**Comment by b1acksun** [comment]
https://github.com/GolosChain/golos.io/pull/171

**Comment by daryasattarova** [comment]
![image](https://user-images.githubusercontent.com/42342756/60664931-ca0c3e00-9e6b-11e9-9db3-d8e7fe98510e.png)
