### ISSUE TITLE
Статус подписки на юзеров в модалках

### ISSUE THREAD

**Issue by beautyfree** [GolosChain/golos.io#155]

**Comment by daryasattarova** [comment]
сейчас статус не меняется

**Comment by beautyfree** [comment]
в каких кейсах?

**Comment by daryasattarova** [comment]
![image](https://user-images.githubusercontent.com/42342756/60723022-2d18d600-9f3b-11e9-9357-6e77fdde81a1.png)
и во вкладке "активность" нужно проверить

**Comment by beautyfree** [comment]
Было решено не делать отдачу этого статуса в api, поэтому кнопку просто скрываем и делать пока не будем
