### ISSUE TITLE
Убрать символ из диалогов кошелька

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/golos.io#192]
![image.png](https://images.zenhubusercontent.com/5a27458f8a75884b908a072e/ed94cb62-816d-47f2-8079-e60c91878f6e)

**Comment by daryasattarova** [comment]
символ остался

**Comment by daryasattarova** [comment]
![image](https://user-images.githubusercontent.com/42342756/62606831-aeca9d80-b905-11e9-96db-33a34d2d9071.png)

**Comment by beautyfree** [comment]
Это это не диалог кошелька(
Тут речь была о диалог конвератции, переводов и т.п
