### ISSUE TITLE
Реализовать возможность зарегистрироваться как делегат приложения golos

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/golos.io#36]
1. Если пользователь, не являющийся делегатом заходит на страницу golos.io/~witnesses, отображаем кнопку "Стать делегатом"
2. При нажатии на эту кнопку открываем модалку, в которой предлагаем пользователю вставить на пост делегата
3. Если на страницу golos.io/~witnesses заходит пользователь, который являетя делегатом, отображаем кнопку "Управление сообществом", при нажатии на которую происходит переход на панель управления

**Comment by daryasattarova** [comment]
нет кнопки "управление сообществом". есть только "снять полномочия делегата"
