### ISSUE TITLE
Плашка технической работы с локализацией и статусами, авторизация ff

### ISSUE THREAD

**Issue by beautyfree** [GolosChain/golos.io#381]

**Comment by MachtFrei** [comment]
UPD:  
надо обновить текст и уменьшить плашку 

новый текст:

Мы запустили все основные сервисы сайта golos.io на новой кодовой базе блокчейна CyberWay!
Просим вас сообщать о всех найденных недочетах и ошибках в канал, а также создавать задачи (issues) на гитхабе.

**Comment by daryasattarova** [comment]
убрать лишние белые пустоты
![image](https://user-images.githubusercontent.com/42342756/63261401-14b30f80-c28c-11e9-9193-968878ab86ff.png)
