### ISSUE TITLE
Ошибка при отрытии ранее размещенных ссылок

### ISSUE THREAD

**Issue by den455** [GolosChain/golos.io#412]
Коллеги доброе утро. Просьба исправить баг с открытием ссылок. Получилась не приятная ситуация, многие участвовали в Баунти и теперь все ссылки не видны в интернете, значит люди не получат вознаграждение за их работу. Просьба оперативно исправить этот баг.Этот баг возник из-за того что в адресную строку, тянется новый ник на golos. Например https://golos.io/ico/@den360/colletrix

**Comment by b1acksun** [comment]
https://github.com/GolosChain/golos.io/issues/431
