### ISSUE TITLE
Как восстановить пароль?

### ISSUE THREAD

**Issue by Quazimorda** [GolosChain/golos.io#413]
Как восстановить пароль?

**Comment by rodnikova** [comment]
Мы не можем восстановить ваш пароль, так как не храним данные пользователей. Проверьте, пожалуйста, на устройстве, с которого вы регистрировались, возможно, файл с ключами лежит где-то в загрузках.
В дальнейшем по таким вопросам писать лучше сюда https://t.me/golos_support

**Comment by Quazimorda** [comment]
Да в том-то и дело, что у меня записан ключ, но только один. И при вводе он не подходил, сайт ругался. А сегодня, видимо с испугу, ключ подошёл. ))
