### ISSUE TITLE
Всё пропало

### ISSUE THREAD

**Issue by dymo-vymo** [GolosChain/golos.io#416]
Исчез мой аккаунт вместе с логином, вложенными деньгами и всем содержимым.
@qm7

**Comment by rodnikova** [comment]
Не работает только ссылка на ваш аккаунт, сам он никуда не исчез.
Ссылки мы поправим сегодня-завтра.
Почистите кэш браузера, обновите страницу и попробуйте авторизоваться.

**Comment by dymo-vymo** [comment]
Почистил куки, обновил страницу с очисткой кеша (Ctrl+F5), попытался
авторизоваться:
Invalid master key

пн, 19 авг. 2019 г. в 13:02, rodnikova <notifications@github.com>:

**Comment by Bacher** [comment]
Сам аккаунт у нас есть, https://golos.io/@qm7/wallet

Вопрос в авторизации. Вы меняли пароль с момента создания аккаунта?

**Comment by dymo-vymo** [comment]
Авторизация заработала. Контент тоже постепенно появляется, но пока не до
конца.

вт, 3 сент. 2019 г. в 13:28, Ilya Lebedev <notifications@github.com>:
