### ISSUE TITLE
при переходе на пост лидера появляется ошибка 

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos.io#466]
формируется некорректный урл
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/7a2d6eb7-9372-4868-bf54-4b4ba319d536)
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/9a3e29fa-c2d6-448b-99e8-b55800993751)

**Comment by b1acksun** [comment]
фикс в https://github.com/GolosChain/golos.io/pull/463
