### ISSUE TITLE
Доработать страницу управление сообществом для лидеров голоса

### ISSUE THREAD

**Issue by MachtFrei** [GolosChain/golos.io#533]
~~Добавить все возможные пропоузалы~~ https://github.com/GolosChain/golos.io/issues/565
добавить ссылки на документацию
убрать лорем ипсум

https://cyberway.gitbook.io/ru/v/master-ru/developers/golos_contracts/golos.charge_contract

**Comment by Bacher** [comment]
Подзадачу "Добавить все возможные пропоузалы" выношу в отдельную задачу https://github.com/GolosChain/golos.io/issues/565

**Comment by daryasattarova** [comment]
ошибка при нажатии на emit
![image](https://user-images.githubusercontent.com/42342756/64236273-bd0ada00-cf02-11e9-8a05-cd4b2c6d4586.png)
