### ISSUE TITLE
Ошибка 500 при переходе в блог пользователя

### ISSUE THREAD

**Issue by rodnikova** [GolosChain/golos.io#545]
При переходе из лент в профиль пользователя, переход либо очень медленный, либо выдает ошибку 500
<img width="477" alt="Снимок экрана 2019-09-02 в 13 00 07" src="https://user-images.githubusercontent.com/36824904/64111394-41d3e780-cd8d-11e9-8860-68e22f065181.png">

<img width="420" alt="Снимок экрана 2019-09-02 в 14 25 33" src="https://user-images.githubusercontent.com/36824904/64111508-94ad9f00-cd8d-11e9-9a4e-bfdd2b901fef.png">

А также 500 ошибка возникает при авторизации
Ник пользователя rajskijsad
![photo_2019-09-02 14 45 39](https://user-images.githubusercontent.com/36824904/64112564-74331400-cd90-11e9-8fa0-73ff9aa1afab.jpeg)

**Comment by Bacher** [comment]
Иван сделал фикс на беке. Сейчас отдается быстро. Перевожу в QA.

**Comment by daryasattarova** [comment]
проверила переход по https://golos.io/@nefabula, переход осуществляется быстро
