### ISSUE TITLE
Некорректное отображение Силы Голоса в балансе пользователя

### ISSUE THREAD

**Issue by rodnikova** [GolosChain/golos.io#548]
Пользователи жалуются, что Сила Голоса на балансе понемногу уменьшается

@sergeymironenko
сегодня в 08:02 и 12:15
![Баланс_@sergeymironenko](https://user-images.githubusercontent.com/36824904/64113139-29b29700-cd92-11e9-8250-af78c6bdcdea.jpg)

@ladyzarulem
<img width="475" alt="Снимок экрана 2019-09-02 в 11 30 18" src="https://user-images.githubusercontent.com/36824904/64113701-a2662300-cd93-11e9-9f51-c63d648c8f93.png">

**Comment by beautyfree** [comment]
Эта проблема решается в сервисе wallet @IvanBlacky
