### ISSUE TITLE
Ошибка при любом действии сразу после регистрации

### ISSUE THREAD

**Issue by chinpu** [GolosChain/golos.io#589]
Post submitting failed: vesting balance doesn't exist
 
![2019-09-05 11 38 34](https://user-images.githubusercontent.com/31181445/64412994-5966e500-d099-11e9-8e30-66bf87ed6f66.jpg)
![2019-09-06 11 29 04](https://user-images.githubusercontent.com/31181445/64413099-903cfb00-d099-11e9-8840-5f02073f7ae8.jpg)

**Comment by b1acksun** [comment]
фикс https://github.com/GolosChain/golos.io/pull/608
