### ISSUE TITLE
Добавить возможность создания предложений (proposal) из произвольной транзакции

### ISSUE THREAD

**Issue by Bacher** [GolosChain/golos.io#668]
Полное описание тут: https://github.com/GolosChain/Questions-and-Answers/issues/34

**Comment by MachtFrei** [comment]
т.к. добавлять мемо сложно было решено сделать ссылки для каждого пропоузала и писать к ним посты посему в задачу добавляется два улучшения

1) ссылки для каждого пропоузала
2) парсинг юзернеймов внутри страниц с пропоузалами
