### ISSUE TITLE
Открытие TransferDialog через URL

### ISSUE THREAD

**Issue by b1acksun** [GolosChain/golos.io#677]
https://golos.io/@b1acksun/wallet?dialog=transfer&to=bacher&amount=10&token=golos&memo=test

**Comment by gropox** [comment]
а можно было бы в урл не указывать аккаунт отправителя? Взять залогиненного. Тогда больше возможностей будет. К примеру линк под донат.

**Comment by b1acksun** [comment]
Для донатов есть кнопки

**Comment by gropox** [comment]
Это не то во первых,  и всего лишь пример. К примеру не будь отправителя в url, я мог бы кинуть ссылку где угодно с просьбой перевести. Или отправить пользователя со стороннего сайта сделатььперевод на голос.ио. Кнопку эту  под донаты я просил еще в 2017-ом, и не с такаим функционалом как сейчас. Это кто то из разрабов по своему интерпретировал мою просьбу, а теперь держитесь за нее.

Хотелось бы, что бы голос выступал посредником в переводе и не такая жёсткая конструкция была.

**Comment by gropox** [comment]
Кстати да. Если можно, добавьте пожалуйста выбор домена. Дело в том, что могут быть зарегистрированы аккаунты в Сайбервее, к примеру giveme.money, и то же самое могут сделать в домене golos. Если указать в ссылке просто to=giveme.money, то голос подставит пользователя из домена голоса. Что конечно с точки зрения приложения правильно, но для стороннего приложения уже может быть фатально, так как другие могут подставлять свои аккаунты и просить сделать перевод на подставной адрес. 

Вот и предлагаю, сделать либо дополнительный аттрибут `domain="~"` (для адреса сyberway) `domain="gls"` (имя в домене gls), либо сделать возможность задавать домен в поле to. to=ropox@gls или to=ropox@~ (для домена cyberway)

как то так.

**Comment by gropox** [comment]
Вопрос с ссылкой без отправителя снимается )) Конечно это не то, что требуется, но если в url указать любой существующий аккаунт и открыть диалог, то в бакграунде все равно подгружается залогиненный пользователь, с его балансом и перевод осуществляется уже от имени залогиненного пользователя.
