### ISSUE TITLE
Неверное значение СГ в кошельке.

### ISSUE THREAD

**Issue by gropox** [GolosChain/golos.io#701]
В кошельке показывает неверную сумму СГ. Процентов на 10% больше. Плюс сумма постоянно плавает. Чеще в меньшую сторону, что вызывает волнение в массах.

К примеру у меня сейчас на вестинговом счету 2383174550.060346 GOLOS

![image](https://user-images.githubusercontent.com/26039472/66765614-97cb9d00-eeac-11e9-8556-22cd4ee49b0c.png)

Токенов на счету gls.vesting 130113824.107 GOLOS

![image](https://user-images.githubusercontent.com/26039472/66765724-d06b7680-eeac-11e9-8aaa-527187733a9e.png)

Суммарное количество вестингов 43388471496.4764254

![image](https://user-images.githubusercontent.com/26039472/66765806-f7c24380-eeac-11e9-8df5-356f0922ae4e.png)

Тоесть моя СГ должна быть 2383174550.060346 * 130113824.107 / 43388471496.4764254 = 714668,997 GP

![image](https://user-images.githubusercontent.com/26039472/66766047-7b7c3000-eead-11e9-9cd2-5684b708bb81.png)

Сайт же показывает 
737536.535 GP

![image](https://user-images.githubusercontent.com/26039472/66765991-57205380-eead-11e9-96c9-ec79f6b50795.png)

Причем сумма постоянно плавает в обе стороны.

**Comment by b1acksun** [comment]
Пофиксили
![image](https://user-images.githubusercontent.com/3322340/66946136-fa619c00-f058-11e9-98a1-150410003be4.png)
