### ISSUE TITLE
Ошибка перехода со страницы комментариев и ответов

### ISSUE THREAD

**Issue by beautyfree** [GolosChain/golos.io#725]
https://trello.com/c/aVm7OFtI/32-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D1%85%D0%BE%D0%B4%D0%B0-%D1%81%D0%BE-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B5%D0%B2-%D0%B8-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%BE%D0%B2

**Comment by Lex-Ai** [comment]
Спс, исправление по ссылкам вижу, а по первой части из трелло, чтобы переход был на сам коммент, проблема в другом или это просто позже?
