### ISSUE TITLE
Выполнение действий контракта используя posting ключ

### ISSUE THREAD

**Issue by b1acksun** [GolosChain/golos.io#8]
При авторизации с помощью posting ключа для экшинов контракта `gls.publish` использовать posting ключ, при других экшинах выводить диалог и запрашивать мастер или активный ключ.

**Comment by daryasattarova** [comment]
не могу авторизоваться  с постинг ключом
![image](https://user-images.githubusercontent.com/42342756/60328539-1e5c7d00-9997-11e9-8122-19ac0de1f9e8.png)

**Comment by b1acksun** [comment]
Видимо была бага, в mainnet авторизирует с постинг ключами
